services:
  analyzer:
    build: .
    container_name: analyzer-api

    ports:
      - "8080:8080"

    volumes:
      - .:/app
      - gradle-cache:/root/.gradle

    tty: true

volumes:
  gradle-cache: