services:
  analyzer:
    build: .
    container_name: analyzer-api

    ports:
      - "8080:8080"

    volumes:
      - .:/app
      - gradle-cache:/root/.gradle

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      ANALYZER_API_KEY: ${ANALYZER_API_KEY}

    tty: true

    depends_on:
      - mysql

    networks:
      - skillchecker-network

  mysql:
    image: mysql:8.0
    container_name: analyzer-mysql

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3310:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - skillchecker-network

volumes:
  gradle-cache:
  mysql-data:

networks:
  skillchecker-network:
    external: true