spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  analyzer:

  api-key: ${ANALYZER_API_KEY}